### ISSUE TITLE
Stuck on Loading Channels

### ISSUE THREAD

**Issue by Aayush9029** [cryptoAlgorithm/Swiftcord#18] opened 2022-05-08 02:37 UTC
**Describe the bug**

**To Reproduce**

1. Login in Swiftcord
2. Close App
3. Open App

**Expected behavior**
Show Channels, Messages ... Views

**Screenshots**
![CleanShot 2022-05-07 at 22 34 22@2x](https://user-images.githubusercontent.com/43297314/167279335-83a40779-c58d-4748-a605-1e959f817cbb.png)

**Logs**
> Adding a better logging system might be required. *to-do* 
![CleanShot 2022-05-07 at 22 36 16@2x](https://user-images.githubusercontent.com/43297314/167279361-a1ab236b-3a5d-4ac2-a2eb-f4ca12b8e178.png)

**Comment by cryptoAlgorithm** [comment] 2022-05-08 02:37
Duplicate of #15

**Comment by cryptoAlgorithm** [comment] 2022-05-08 02:40
Running from source in Xcode would provide logs, or you can look in console.app. I use OSLog, which is apple's native logging system for macOS. Sensitive data like payloads containing your token are redacted (when they are persisted in console.app, not in Xcode).

**Closed** 2022-05-08 02:40 UTC
Labels: bug
